create database store

CREATE TABLE STORE(
Transaction ID VARCHAR(50),
Date DATE,
Customer ID PRIMERY KEY,
Gender  VARCHAR(50),
Age INT,
Product Category VARCHAR(50),
Quantity NUMERIC,
Price per Unit NUMERIC,
Total Amount NUMERIC
);

SELECT * FROM STORE

--- TOTAL COUSTOMERS ---

SELECT COUNT(*) AS COUNT
FROM STORE

--- TOP SELLING PRODUCT ---

SELECT PRODUCT_CATEGORY ,SUM(TOTAL_AMOUNT) AS AMOUNT
FROM STORE
GROUP BY PRODUCT_CATEGORY


---SUM(SALE), AVG(PROFIT), COUNT(*), CATEGORY

SELECT PRODUCT_CATEGORY, SUM(TOTAL_AMOUNT) AS SALE, AVG(TOTAL_AMOUNT) AS AVG_PROFIT,
COUNT(*) AS COUNT
FROM STORE
GROUP BY PRODUCT_CATEGORY

--- HAVING>100000 ONLY CATEGORY ---

SELECT PRODUCT_CATEGORY, SUM(TOTAL_AMOUNT) AS SALE
FROM STORE
GROUP BY PRODUCT_CATEGORY
HAVING PRODUCT_CATEGORY> '100000'

--- MONTHLY SALE REPORT AND CUSTOMER ID ---

SELECT TO_CHAR(ORDER_DATE,' MM-YYYY') AS MONTH,
SUM(TOTAL_AMOUNT) AS MONTHL_SALE
FROM STORE 
GROUP BY MONTH
ORDER BY MONTH